export const BLOCK_IDS = {
  air: 0,
  grass: 1,
  dirt: 2,
  stone: 3,
  sand: 4,
  water: 5,
  wood: 6,
  leaves: 7,
  grassPlant: 8,
  rock: 9,
  sandstone: 10,
  planks: 11,
  lootChest: 12,
  furnace: 13,
  campfire: 14,
  ironOre: 15,
};

export const BLOCK_DEFINITIONS = {
  [BLOCK_IDS.air]: {
    id: BLOCK_IDS.air,
    name: 'Air',
    material: 'none',
    texture: null,
    hardness: 0,
    toolType: 'none',
    drop: null,
    collision: false,
    transparent: true,
    renderable: false,
    occludes: false,
    color: '#000000',
  },
  [BLOCK_IDS.grass]: {
    id: BLOCK_IDS.grass,
    name: 'Grass',
    material: 'organic',
    texture: null,
    hardness: 0.8,
    toolType: 'hand',
    drop: BLOCK_IDS.dirt,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#2f8f45',
  },
  [BLOCK_IDS.dirt]: {
    id: BLOCK_IDS.dirt,
    name: 'Dirt',
    material: 'soil',
    texture: null,
    hardness: 1,
    toolType: 'hand',
    drop: BLOCK_IDS.dirt,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#8a6139',
  },
  [BLOCK_IDS.stone]: {
    id: BLOCK_IDS.stone,
    name: 'Stone',
    material: 'rock',
    texture: null,
    hardness: 3,
    toolType: 'pickaxe',
    drop: BLOCK_IDS.stone,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#828985',
  },
  [BLOCK_IDS.sand]: {
    id: BLOCK_IDS.sand,
    name: 'Sand',
    material: 'granular',
    texture: null,
    hardness: 1,
    toolType: 'hand',
    drop: BLOCK_IDS.sand,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#d9c36d',
  },
  [BLOCK_IDS.water]: {
    id: BLOCK_IDS.water,
    name: 'Water',
    material: 'liquid',
    texture: null,
    hardness: 0.2,
    toolType: 'hand',
    drop: BLOCK_IDS.water,
    collision: false,
    transparent: true,
    renderable: true,
    occludes: false,
    opacity: 0.58,
    scale: { x: 1, y: 0.82, z: 1 },
    color: '#3c8ed8',
  },
  [BLOCK_IDS.wood]: {
    id: BLOCK_IDS.wood,
    name: 'Wood',
    material: 'organic',
    texture: null,
    hardness: 2,
    toolType: 'axe',
    drop: BLOCK_IDS.wood,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#7a522b',
  },
  [BLOCK_IDS.leaves]: {
    id: BLOCK_IDS.leaves,
    name: 'Leaves',
    material: 'organic',
    texture: null,
    hardness: 0.4,
    toolType: 'hand',
    drop: { itemType: 'consumable', itemId: 'berries', count: 1 },
    collision: true,
    groundCollision: false,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#237d34',
  },
  [BLOCK_IDS.grassPlant]: {
    id: BLOCK_IDS.grassPlant,
    name: 'Grass Plant',
    material: 'organic',
    texture: null,
    hardness: 0.2,
    toolType: 'hand',
    drop: { itemType: 'resource', itemId: 'fiber', count: 1 },
    collision: false,
    transparent: true,
    renderable: true,
    occludes: false,
    opacity: 0.88,
    scale: { x: 0.22, y: 0.72, z: 0.22 },
    color: '#46b653',
  },
  [BLOCK_IDS.rock]: {
    id: BLOCK_IDS.rock,
    name: 'Rock',
    material: 'rock',
    texture: null,
    hardness: 3,
    toolType: 'pickaxe',
    drop: BLOCK_IDS.rock,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 0.78, y: 0.58, z: 0.78 },
    color: '#6d746f',
  },
  [BLOCK_IDS.sandstone]: {
    id: BLOCK_IDS.sandstone,
    name: 'Sandstone',
    material: 'rock',
    texture: null,
    hardness: 2,
    toolType: 'pickaxe',
    drop: BLOCK_IDS.sandstone,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#bfa562',
  },
  [BLOCK_IDS.planks]: {
    id: BLOCK_IDS.planks,
    name: 'Planks',
    material: 'wood',
    texture: null,
    hardness: 1.4,
    toolType: 'axe',
    drop: BLOCK_IDS.planks,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#b47a3c',
  },
  [BLOCK_IDS.lootChest]: {
    id: BLOCK_IDS.lootChest,
    name: 'Loot Chest',
    material: 'container',
    texture: null,
    hardness: 1.2,
    toolType: 'axe',
    drop: { itemType: 'resource', itemId: 'lootCache', count: 1 },
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 0.9, y: 0.72, z: 0.9 },
    color: '#8b5a2b',
  },
  [BLOCK_IDS.furnace]: {
    id: BLOCK_IDS.furnace,
    name: 'Furnace',
    material: 'station',
    texture: null,
    hardness: 3.2,
    toolType: 'pickaxe',
    drop: BLOCK_IDS.furnace,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#4d5654',
  },
  [BLOCK_IDS.campfire]: {
    id: BLOCK_IDS.campfire,
    name: 'Campfire',
    material: 'station',
    texture: null,
    hardness: 0.8,
    toolType: 'hand',
    drop: { itemType: 'resource', itemId: 'coal', count: 1 },
    collision: false,
    transparent: true,
    renderable: true,
    occludes: false,
    opacity: 0.94,
    scale: { x: 0.78, y: 0.32, z: 0.78 },
    color: '#d17839',
  },
  [BLOCK_IDS.ironOre]: {
    id: BLOCK_IDS.ironOre,
    name: 'Iron Ore',
    material: 'ore',
    texture: null,
    hardness: 4.5,
    toolType: 'pickaxe',
    drop: { itemType: 'resource', itemId: 'ironOre', count: 1 },
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#947a6a',
  },
};

export function isSolidBlock(blockId) {
  return blockId !== BLOCK_IDS.air && BLOCK_DEFINITIONS[blockId]?.collision === true;
}

export function isGroundColliderBlock(blockId) {
  return isSolidBlock(blockId) && BLOCK_DEFINITIONS[blockId]?.groundCollision !== false;
}

export function isRenderableBlock(blockId) {
  return BLOCK_DEFINITIONS[blockId]?.renderable === true;
}

export function isOccludingBlock(blockId) {
  return BLOCK_DEFINITIONS[blockId]?.occludes === true;
}
