export const BLOCK_IDS = {
  air: 0,
  grass: 1,
  dirt: 2,
  stone: 3,
  sand: 4,
  water: 5,
  wood: 6,
  leaves: 7,
  grassPlant: 8,
  rock: 9,
  sandstone: 10,
};

export const BLOCK_DEFINITIONS = {
  [BLOCK_IDS.air]: {
    id: BLOCK_IDS.air,
    name: 'Air',
    material: 'none',
    texture: null,
    hardness: 0,
    toolType: 'none',
    drop: null,
    collision: false,
    transparent: true,
    renderable: false,
    occludes: false,
    color: '#000000',
  },
  [BLOCK_IDS.grass]: {
    id: BLOCK_IDS.grass,
    name: 'Grass',
    material: 'organic',
    texture: null,
    hardness: 0.8,
    toolType: 'hand',
    drop: BLOCK_IDS.dirt,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#2f8f45',
  },
  [BLOCK_IDS.dirt]: {
    id: BLOCK_IDS.dirt,
    name: 'Dirt',
    material: 'soil',
    texture: null,
    hardness: 1,
    toolType: 'hand',
    drop: BLOCK_IDS.dirt,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#8a6139',
  },
  [BLOCK_IDS.stone]: {
    id: BLOCK_IDS.stone,
    name: 'Stone',
    material: 'rock',
    texture: null,
    hardness: 3,
    toolType: 'pickaxe',
    drop: BLOCK_IDS.stone,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#828985',
  },
  [BLOCK_IDS.sand]: {
    id: BLOCK_IDS.sand,
    name: 'Sand',
    material: 'granular',
    texture: null,
    hardness: 1,
    toolType: 'hand',
    drop: BLOCK_IDS.sand,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#d9c36d',
  },
  [BLOCK_IDS.water]: {
    id: BLOCK_IDS.water,
    name: 'Water',
    material: 'liquid',
    texture: null,
    hardness: 0.2,
    toolType: 'hand',
    drop: BLOCK_IDS.water,
    collision: false,
    transparent: true,
    renderable: true,
    occludes: false,
    opacity: 0.58,
    scale: { x: 1, y: 0.82, z: 1 },
    color: '#3c8ed8',
  },
  [BLOCK_IDS.wood]: {
    id: BLOCK_IDS.wood,
    name: 'Wood',
    material: 'organic',
    texture: null,
    hardness: 2,
    toolType: 'axe',
    drop: BLOCK_IDS.wood,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#7a522b',
  },
  [BLOCK_IDS.leaves]: {
    id: BLOCK_IDS.leaves,
    name: 'Leaves',
    material: 'organic',
    texture: null,
    hardness: 0.4,
    toolType: 'hand',
    drop: BLOCK_IDS.leaves,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#237d34',
  },
  [BLOCK_IDS.grassPlant]: {
    id: BLOCK_IDS.grassPlant,
    name: 'Grass Plant',
    material: 'organic',
    texture: null,
    hardness: 0.2,
    toolType: 'hand',
    drop: BLOCK_IDS.grassPlant,
    collision: false,
    transparent: true,
    renderable: true,
    occludes: false,
    opacity: 0.88,
    scale: { x: 0.22, y: 0.72, z: 0.22 },
    color: '#46b653',
  },
  [BLOCK_IDS.rock]: {
    id: BLOCK_IDS.rock,
    name: 'Rock',
    material: 'rock',
    texture: null,
    hardness: 3,
    toolType: 'pickaxe',
    drop: BLOCK_IDS.rock,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 0.78, y: 0.58, z: 0.78 },
    color: '#6d746f',
  },
  [BLOCK_IDS.sandstone]: {
    id: BLOCK_IDS.sandstone,
    name: 'Sandstone',
    material: 'rock',
    texture: null,
    hardness: 2,
    toolType: 'pickaxe',
    drop: BLOCK_IDS.sandstone,
    collision: true,
    transparent: false,
    renderable: true,
    occludes: true,
    scale: { x: 1, y: 1, z: 1 },
    color: '#bfa562',
  },
};

export function isSolidBlock(blockId) {
  return blockId !== BLOCK_IDS.air && BLOCK_DEFINITIONS[blockId]?.collision === true;
}

export function isRenderableBlock(blockId) {
  return BLOCK_DEFINITIONS[blockId]?.renderable === true;
}

export function isOccludingBlock(blockId) {
  return BLOCK_DEFINITIONS[blockId]?.occludes === true;
}
